"""
HTML Report Generator
Creates human-readable HTML reports with styling
"""

from datetime import datetime
from pathlib import Path
from typing import Dict
from config import REPORTS_DIR


class HTMLReporter:
    def __init__(self, scan_data: Dict):
        self.scan_data = scan_data
        self.report_path = None
    
    def generate(self, filename: str = None) -> Path:
        """
        Generate HTML report
        Returns: Path to generated report
        """
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            target = self.scan_data.get('target', 'unknown')
            filename = f"scan_{target}_{timestamp}.html"
        
        self.report_path = REPORTS_DIR / filename
        
        html_content = self._build_html()
        
        with open(self.report_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        print(f"[+] HTML report saved: {self.report_path}")
        return self.report_path
    
    def _build_html(self) -> str:
        """Build complete HTML report"""
        target = self.scan_data.get('target', 'Unknown')
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Network Scan Report - {target}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ 
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: #f5f5f5;
            padding: 20px;
            line-height: 1.6;
        }}
        .container {{ 
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        h1 {{ 
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }}
        h2 {{
            color: #34495e;
            margin-top: 30px;
            margin-bottom: 15px;
            border-left: 4px solid #3498db;
            padding-left: 15px;
        }}
        .info-box {{
            background: #ecf0f1;
            padding: 15px;
            border-radius: 5px;
            margin: 15px 0;
        }}
        .info-box p {{
            margin: 8px 0;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }}
        th, td {{
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }}
        th {{
            background-color: #3498db;
            color: white;
            font-weight: bold;
        }}
        tr:hover {{
            background-color: #f5f5f5;
        }}
        .status-open {{ color: #27ae60; font-weight: bold; }}
        .status-closed {{ color: #e74c3c; }}
        .status-filtered {{ color: #f39c12; }}
        .severity-critical {{ 
            background: #e74c3c;
            color: white;
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 12px;
        }}
        .severity-high {{ 
            background: #e67e22;
            color: white;
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 12px;
        }}
        .severity-medium {{ 
            background: #f39c12;
            color: white;
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 12px;
        }}
        .severity-low {{ 
            background: #95a5a6;
            color: white;
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 12px;
        }}
        .footer {{
            margin-top: 40px;
            padding-top: 20px;
            border-top: 2px solid #ecf0f1;
            text-align: center;
            color: #7f8c8d;
            font-size: 14px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🔍 Network Security Scan Report</h1>
        
        <div class="info-box">
            <p><strong>Target:</strong> {target}</p>
            <p><strong>Scan Time:</strong> {timestamp}</p>
            <p><strong>Tool:</strong> Network Security Analyzer v1.0.0</p>
        </div>

        {self._build_port_scan_section()}
        {self._build_service_detection_section()}
        {self._build_os_detection_section()}
        {self._build_firewall_section()}
        {self._build_topology_section()}
        {self._build_vulnerability_section()}
        
        <div class="footer">
            <p>Generated by Network Security Analyzer</p>
            <p>For authorized security testing only</p>
        </div>
    </div>
</body>
</html>
"""
        return html
    
    def _build_port_scan_section(self) -> str:
        """Build port scan results section"""
        port_data = self.scan_data.get('port_scan', {})
        open_ports = port_data.get('open_ports', [])
        filtered_ports = port_data.get('filtered_ports', [])
        total_scanned = port_data.get('total_scanned', 0)
        
        html = f"""
        <h2>📡 Port Scan Results</h2>
        <div class="info-box">
            <p><strong>Total Ports Scanned:</strong> {total_scanned}</p>
            <p><strong>Open Ports:</strong> <span class="status-open">{len(open_ports)}</span></p>
            <p><strong>Filtered Ports:</strong> <span class="status-filtered">{len(filtered_ports)}</span></p>
        </div>
        """
        
        if open_ports:
            html += "<p><strong>Open Ports:</strong> " + ", ".join(map(str, open_ports)) + "</p>"
        
        return html
    
    def _build_service_detection_section(self) -> str:
        """Build service detection section"""
        services = self.scan_data.get('services', {})
        
        if not services:
            return ""
        
        html = """
        <h2>🔧 Detected Services</h2>
        <table>
            <tr>
                <th>Port</th>
                <th>Service</th>
                <th>Version</th>
                <th>Banner</th>
            </tr>
        """
        
        for port, info in services.items():
            service = info.get('service', 'unknown')
            version = info.get('version', 'unknown')
            banner = info.get('banner', 'N/A')
            if len(banner) > 60:
                banner = banner[:60] + "..."
            
            html += f"""
            <tr>
                <td>{port}</td>
                <td>{service}</td>
                <td>{version}</td>
                <td style="font-size:12px; font-family:monospace;">{banner}</td>
            </tr>
            """
        
        html += "</table>"
        return html
    
    def _build_os_detection_section(self) -> str:
        """Build OS detection section"""
        os_info = self.scan_data.get('os_detection', {})
        
        if not os_info or os_info.get('detected_os') == 'Unknown':
            return ""
        
        html = f"""
        <h2>💻 Operating System Detection</h2>
        <div class="info-box">
            <p><strong>Detected OS:</strong> {os_info.get('detected_os', 'Unknown')}</p>
            <p><strong>Confidence:</strong> {os_info.get('confidence', 'Low')}</p>
            <p><strong>TTL:</strong> {os_info.get('ttl', 'N/A')}</p>
            <p><strong>TCP Window Size:</strong> {os_info.get('window_size', 'N/A')}</p>
            <p><strong>DF Flag:</strong> {os_info.get('df_flag', 'N/A')}</p>
        </div>
        """
        
        return html
    
    def _build_firewall_section(self) -> str:
        """Build firewall detection section"""
        fw_info = self.scan_data.get('firewall_detection', {})
        
        if not fw_info:
            return ""
        
        detected = fw_info.get('firewall_detected', False)
        status = "🔥 Detected" if detected else "✅ Not Detected"
        
        html = f"""
        <h2>🛡️ Firewall Detection</h2>
        <div class="info-box">
            <p><strong>Status:</strong> {status}</p>
        """
        
        if fw_info.get('filtering_behavior'):
            html += "<p><strong>Behavior:</strong></p><ul>"
            for behavior in fw_info['filtering_behavior']:
                html += f"<li>{behavior}</li>"
            html += "</ul>"
        
        html += "</div>"
        return html
    
    def _build_topology_section(self) -> str:
        """Build topology mapping section"""
        topo = self.scan_data.get('topology', {})
        hops = topo.get('hops', [])
        
        if not hops:
            return ""
        
        html = """
        <h2>🗺️ Network Topology</h2>
        <table>
            <tr>
                <th>Hop</th>
                <th>IP Address</th>
                <th>Hostname</th>
                <th>RTT</th>
            </tr>
        """
        
        for hop in hops:
            if 'error' in hop:
                continue
            html += f"""
            <tr>
                <td>{hop.get('hop', '-')}</td>
                <td>{hop.get('ip', '-')}</td>
                <td>{hop.get('hostname', '-')}</td>
                <td>{hop.get('rtt', '-')}</td>
            </tr>
            """
        
        html += "</table>"
        return html
    
    def _build_vulnerability_section(self) -> str:
        """Build vulnerability correlation section"""
        vulns = self.scan_data.get('vulnerabilities', {})
        
        if not vulns:
            return ""
        
        html = "<h2>⚠️ Vulnerability Correlation (CVE Database)</h2>"
        
        for port, cve_list in vulns.items():
            if not cve_list or 'error' in cve_list[0]:
                continue
            
            html += f"<h3>Port {port}</h3><table>"
            html += "<tr><th>CVE ID</th><th>Severity</th><th>Score</th><th>Description</th></tr>"
            
            for cve in cve_list[:5]:  # Limit to 5 per port
                severity = cve.get('severity', 'N/A')
                severity_class = f"severity-{severity.lower()}" if severity != 'N/A' else ''
                description = cve.get('description', 'No description')
                if len(description) > 100:
                    description = description[:100] + "..."
                
                html += f"""
                <tr>
                    <td>{cve.get('cve_id', 'N/A')}</td>
                    <td><span class="{severity_class}">{severity}</span></td>
                    <td>{cve.get('score', 'N/A')}</td>
                    <td style="font-size:13px;">{description}</td>
                </tr>
                """
            
            html += "</table>"
        
        return html
